- hosts: localhost
  vars_files:
          - mysecure.yml
  tasks:
          - name: Pro OS in AWS
            ec2:
                    key_name: "AccesKey"
                    instance_type: t2.micro
                    image: "ami-0a780d5bac870126a"
                    wait: true
                    count: 1
                    vpc_subnet_id: "subnet-5f151037"
                    region: "ap-south-1"
                    state: present
                    group_id: "sg-d11a4cb3"
                    aws_access_key: "{{ myuser }}"
                    aws_secret_key: "{{ mypass }}"
                    count_tag:
                            Name: Demo
                    instance_tags:
                            Name: Demo
# export AWS_REGION: "AP-SOUTH-1"
# export AWS_ACCESS_KEY: "XXXXXXXXXXX"
#AWS_SECRET_ACCESS_KEY: "XXXXXXXXXXXXXXXXXXXXXXX345"

	- name: Install Webserver
	  package: "httpd"
	  state: present
	  services: started
	- name: copy data
      	  copy:
              src: "/mycode/web/index.html"
              dest: "/var/www/html"
    	- name: image copy
       	  copy:
              src: "/mycode/web/1.jpg"
              dest: "/var/www/html"
